server:
  port: 3344

spring:
  application:
    name: cloud-config-center
  cloud:
    config:
      server:
        git:
          # 获取github仓库地址
#          uri: git@github.com:lokn309/springcloud-config.git
          # 采用此次的的uri，可以连接到github，其它的方式会导致连接失败，或是无权限
          uri: https://github.com/lokn309/springcloud-config.git
          # 搜索目录
          search-paths:
            - springcloud-config
          username: lokn309
          password: xxxxxxxxxxxxx
        # 读取分支
        label: main
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka

# rabbitmq相关配置，暴露bus刷新配置的端点
management:
  endpoints:
    web:
      exposure:
        include: "bus-refresh"
