server:
  port: 8401

spring:
  application:
    name: cloudalibaba-sentinel-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:1111
    sentinel:
      transport:
        # 配置sentinel dashbord 地址
        dashboard: localhost:8080
        # 默认8719端口，假如端口被占用自动从8719开始依次+1扫描，直至找到可用端口
        port: 8719

management:
  endpoints:
    web:
      exposure:
        include: '*'
